---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bc250-patched-kernel
description: My personal Bazzite OS image with patched kernel raising GPU max frequency to 2230 MHz (from 2000 MHz), lowering min GPU frequency to 350 MHz (from 1000 MHz), and oberon-governor included.

# base image to build on top of
base-image: ghcr.io/ublue-os/bazzite
image-version: 42 # latest is also supported

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - oberon-governor.service

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/vietsman/patched-kernel-bc250/repo/fedora-%OS_VERSION%/vietsman-patched-kernel-bc250.repo
    install:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core

  - type: signing
